"""Generate the Go2+D1 environment from UniFP's B2Z1 environment.

The upstream file is 2344 lines and hardcodes the B2Z1 DOF layout (12 legs, arm at 12:17,
two held joints at the end) as literal slice bounds in about twenty places. Rather than keep
a forked copy and lose track of what was changed, this applies an explicit list of
substitutions to the upstream file and asserts the expected hit count for each, so the port
fails loudly if upstream ever differs from the revision it was written against.

Every substitution either (a) replaces a literal arm-slice bound with the same quantity read
from the config, so 17 actions becomes 18, or (b) replaces a hardcoded Z1 gripper gain with a
config value. No reward, observation, curriculum or algorithm logic is touched.

Usage:  python port_env.py [<UniFP checkout>]
"""

import os
import sys

UPSTREAM_REV = "68847a070f88d731058c3d8476929bc3b205f5bd"

SRC = "legged_gym/envs/b2/legged_robot_b2z1_pos_force.py"
DST = "legged_gym/envs/go2d1/legged_robot_go2d1_pos_force.py"

HEADER = '''"""Go2 + D1 position/force environment.

GENERATED by unifp_go2d1/port_env.py from UniFP's legged_robot_b2z1_pos_force.py at
{rev} (BSD-3-Clause; see third_party/UniFP/NOTICE.md).
Do not edit this file directly -- edit port_env.py and regenerate, so the diff from upstream
stays auditable.
"""
'''

# (old, new, expected occurrences, why)
SUBS = [
    ("from legged_gym.envs.b2.b2z1_pos_force_config import B2Z1PosForceRoughCfg",
     "from legged_gym.envs.go2d1.go2d1_pos_force_config import Go2D1PosForceRoughCfg",
     1, "point at the Go2+D1 config"),

    ("class LeggedRobot_b2z1_pos_force(BaseTask):",
     "class LeggedRobot_go2d1_pos_force(BaseTask):",
     1, "rename the class"),

    ("cfg: B2Z1PosForceRoughCfg",
     "cfg: Go2D1PosForceRoughCfg",
     1, "type annotation follows the config"),

    # --- arm slice bounds: B2Z1 has 5 controlled arm joints (12:17), Go2+D1 has 6 (12:18) ---
    ("[:, 12:17]",
     "[:, 12:self.num_actions]",
     6, "arm-only reward terms: torques, dof_vel, energy, dof_acc, action_rate, torque smoothness"),

    ("self.dof_pos[env_ids, 12:17] +=",
     "self.dof_pos[env_ids, 12:self.num_actions] +=",
     1, "reset perturbs the arm joints"),

    ("(torch.abs(self.torques[:,12:17]) - self.torque_limits[12:17]",
     "(torch.abs(self.torques[:,12:self.num_actions]) - self.torque_limits[12:self.num_actions]",
     1, "arm torque-limit penalty"),

    # --- action-width slices: 17 -> 18 ---
    ("self.motor_strength[:, :17] - 1",
     "self.motor_strength[:, :self.num_actions] - 1",
     1, "privileged obs: per-actuator strength"),

    ("self.actions[:, :17]",
     "self.actions[:, :self.num_actions]",
     2, "previous actions in the actor and critic observations"),

    ("out_of_limits[:, :17]",
     "out_of_limits[:, :self.num_actions]",
     1, "joint-limit penalty covers the actuated joints"),

    ("(self.num_envs, 5), device=self.device)",
     "(self.num_envs, self.cfg.env.num_actions - 12), device=self.device)",
     1, "arm motor-strength randomisation is per arm action"),

    # --- held (non-action) joints: the Z1's revolute gripper vs the D1's prismatic jaws ---
    ("last_torque = 64. * (torch.zeros([actions_scaled.shape[0], 1], device=actions_scaled.device) "
     "+ self.default_dof_pos[:, -2] - self.dof_pos[:, -2:-1]) - 1.5 * self.dof_vel[:, -2:-1]",
     "last_torque = self.cfg.control.gripper_stiffness * (torch.zeros([actions_scaled.shape[0], 1], "
     "device=actions_scaled.device) + self.default_dof_pos[:, -2] - self.dof_pos[:, -2:-1]) "
     "- self.cfg.control.gripper_damping * self.dof_vel[:, -2:-1]",
     1, "first held joint: Z1 gain 64 N.m/rad -> D1 jaw gain from config (N/m)"),

    ("gripper_torque = 64. * (torch.zeros([actions_scaled.shape[0], 1], device=actions_scaled.device) "
     "+ self.default_dof_pos[:, -1] - self.dof_pos[:, -1:]) - 1.5 * self.dof_vel[:, -1:]",
     "gripper_torque = self.cfg.control.gripper_stiffness * (torch.zeros([actions_scaled.shape[0], 1], "
     "device=actions_scaled.device) + self.default_dof_pos[:, -1] - self.dof_pos[:, -1:]) "
     "- self.cfg.control.gripper_damping * self.dof_vel[:, -1:]",
     1, "second held joint, same change"),
]


def port(unifp_root):
    src_path = os.path.join(unifp_root, SRC)
    text = open(src_path).read()
    original = text
    print(f"porting {SRC} ({len(text.splitlines())} lines)")
    for old, new, expected, why in SUBS:
        found = text.count(old)
        if found != expected:
            raise AssertionError(
                f"expected {expected} occurrence(s) of {old[:60]!r}, found {found}. "
                f"Upstream has changed from {UPSTREAM_REV}; review before regenerating.")
        text = text.replace(old, new)
        print(f"  {expected:2d}x  {why}")
    if text == original:
        raise AssertionError("nothing changed")

    # Nothing may still slice at the B2Z1 arm bound.
    for leftover in ("12:17", ":17]"):
        if leftover in text:
            line = next(i + 1 for i, l in enumerate(text.splitlines()) if leftover in l)
            raise AssertionError(f"{leftover!r} still present at line {line}")

    dst_path = os.path.join(unifp_root, DST)
    os.makedirs(os.path.dirname(dst_path), exist_ok=True)
    open(dst_path, "w").write(HEADER.format(rev=UPSTREAM_REV) + text)
    print(f"wrote {dst_path}")
    return dst_path


if __name__ == "__main__":
    root = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/thesis_b_legacy/UniFP")
    port(root)
